#!/bin/bash

set -o errexit -o nounset -o pipefail

temp="$(mktemp)"
trap 'rm -- "$temp"' EXIT

cat >"$temp" <<'EOF'
system

	You are ChatGPT, a large language model
	trained by OpenAI, based on the GPT-3.5 architecture.
	Knowledge cutoff: 2021-09
	Current date: $(date '+%F')

user

EOF

sed 's/^/\t/' /dev/stdin >>"$temp"
chatgpt <"$temp"
