#!/bin/bash

set -o errexit -o nounset -o pipefail

say() {
	printf '%s\n' "$*" >&2
}

die() {
	printf '%s\n' "$*" >&2
	exit 1
}

add_temperature() {
	local file="$1" t="$2"

	jq --arg 't' "$t" '.temperature = ($t|tonumber)' \
	<"$file" \
	| sponge -- "$file"
}

add_message() {
	local file="$1" role="$2" content="$3"

	jq \
		--arg 'r' "$role" \
		--arg 'c' "$content" \
		'.messages += [{"role": $r, "content": $c}]' \
	<"$file" \
	| sponge -- "$file"
}

build_request() {
	local file="$1" temperature="$2"

	if [[ "$temperature" ]]; then
		add_temperature "$file" "$temperature"
	fi

	local role='' content=''

	local s
	while IFS= read -r s; do
		if [[ "$s" =~ ^[^[:blank:]] ]]; then
			if [[ "$role" ]]; then
				add_message "$file" "$role" "$content"
				content=''
			fi
			read -r role <<<"$s"
			continue
		fi

		content+="${s#$'\t'}"$'\n'
	done

	if [[ "$role" ]]; then
		add_message "$file" "$role" "$content"
	fi
}

#
# configuration
#

CURL=(/usr/bin/curl --silent --fail-with-body)

if rc="$HOME/.chatgptrc"; [[ -f "$rc" && -r "$rc" ]]; then
	source -- "$rc"
fi

#
# resource cleanup
#

cleanup_files=()
trap 'rm -f -- "${cleanup_files[@]}"' EXIT

#
# command-line args
#

TEMPERATURE=

while true; do
	case "$1" in
	-temperature)
		TEMPERATURE="$2"
		shift 2
		;;
	'--')
		shift
		break
		;;
	*)
		break
		;;
	esac
done

if (( $# < 1 )); then
	die 'invalid usage'
fi

#
# handle base_request
#

base_request="$(mktemp)"
cleanup_files+=("$base_request")

if ! "$HOME/.chatgpt.d/$1" >"$base_request"; then
	die 'base request is broken'
fi

#
# build the real request and send it
#

request="$(mktemp)" response="$(mktemp)"
cleanup_files+=("$request" "$response")

cat -- "$base_request" >"$request"

build_request "$request" "$TEMPERATURE"

"${CURL[@]}" \
	-H "Authorization: Bearer $OPENAI_API_KEY" \
	--json "@$request" \
	'https://api.openai.com/v1/chat/completions' \
>"$response" \
|| {
	say "request failed"
	die "$(cat -- "$response")"
}

#
# print the response
#

printf '\n'

jq \
	--raw-output \
	'.choices[0].message.role' \
<"$response"

printf '\n'

jq \
	--raw-output \
	'.choices[0].message.content' \
<"$response" \
| fmt --split-only \
| sed 's/^./	&/'
