#!/bin/bash

set -o errexit -o nounset -o pipefail

temp="$(mktemp)"
trap 'rm -- "$temp"' EXIT

cat >"$temp" <<EOF
user

$(sed 's/^/\t/' /dev/stdin)
EOF

chatgpt "$@" \
<"$temp" \
| sed '1,3d;s/^\t//'
